name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  test:
    name: Test
    uses: ./.github/workflows/ci.yml

  release:
    name: Release
    needs: test
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - run: deno publish

      - name: Create GitHub Release
        run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
